[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking1 = "JCUi4Zym7UHjYPsf9796d3a2KfYyTWRNb35rUvNaSADf"
[programs.devnet]
nft_staking1 = "JCUi4Zym7UHjYPsf9796d3a2KfYyTWRNb35rUvNaSADf"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet =  qqa "~/.config/solana/id.json"
[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=51e0da6e-3012-4def-8966-65a5397ff53d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
